source $VIMRUNTIME/vimrc_example.vim

"PlugIn For Python
"source /usr/share/vim/vimfiles/plugin/python.vim

filetype on
filetype plugin on
filetype indent on

autocmd BufRead,BufNewFile *.py syntax on
autocmd BufRead,BufNewFile *.py set ai
autocmd BufRead,BufNewFile *.py set makeprg=errout\ python\ %
autocmd BufRead,BufNewFile *.py set ts=8 sw=4 softtabstop=4 expandtab
autocmd BufRead,BufNewFile *.py set smarttab smartindent sta
autocmd BufNewFile *.py 0r $HOME/.vim/templates/template.py

autocmd BufNewFile *.sh 0r $HOME/.vim/templates/template.sh

autocmd BufRead,BufNewFile Makefile set ts=8 sts=8 sw=8 noet

"PlugIn For Fortran
"source /usr/share/vim/vimfiles/plugin/fortran.vim

filetype on
filetype plugin on
filetype indent on

let fortran_free_source=1
let fortran_have_tabs=1
autocmd BufRead,BufNewFile *.f90 syntax on
autocmd BufRead,BufNewFile *.f90 set ai
autocmd BufRead,BufNewFile *.f90 set makeprg=errout\ fortran\ %

autocmd BufWritePost *.py silent! execute ':Black'

set nu
set title
set fileencodings=utf-8,cp949
set encoding=utf-8
set tabstop=8 sw=4 softtabstop=4 smarttab expandtab
set nocompatible
set cindent
set ruler
set autowrite
set textwidth=120
set ai showmatch hidden incsearch ignorecase smartcase smartindent hlsearch
set noundofile nobackup noswapfile
set visualbell

map <F5> :wa <CR> :! python % <CR>
map <F6> :q! <CR>
nnoremap <F7> :Black<CR>
